author: Matthew Hassett
email: matt@matthassett.com
github_username:  mhass30 # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
